package com.veroflow.verostay.navigation

object Routes {
    const val SPLASH = "splash"
    const val ONBOARDING = "onboarding"
    const val WELCOME = "welcome"
    const val REGISTER = "register"
    const val LOGIN = "login"
    const val FORGOT_PASSWORD = "forgot_password"
    const val HOME = "home"
    const val SEARCH = "search"
    const val SEARCH_RESULTS = "search_results/{query}"
    const val APARTMENT_DETAILS = "apartment_details/{apartmentId}"
    const val IMAGE_GALLERY = "image_gallery/{apartmentId}"
    const val MAP_VIEW = "map_view/{apartmentId}"
    const val AMENITIES = "amenities/{apartmentId}"
    const val CALENDAR = "calendar/{apartmentId}"
    const val GUEST_SELECTION = "guest_selection/{apartmentId}"
    const val BOOKING_SUMMARY = "booking_summary/{apartmentId}"
    const val PAYMENT = "payment/{apartmentId}"
    const val BOOKING_CONFIRMATION = "booking_confirmation/{bookingId}"
    const val MY_BOOKINGS = "my_bookings"
    const val BOOKING_DETAILS = "booking_details/{bookingId}"
    const val HOST_PROFILE = "host_profile/{hostId}"
    const val CHAT = "chat/{hostId}"
    const val NOTIFICATIONS = "notifications"
    const val FAVORITES = "favorites"
    const val REVIEWS = "reviews/{apartmentId}"
    const val PROFILE = "profile"
    const val EDIT_PROFILE = "edit_profile"
    const val SETTINGS = "settings"
    const val HELP_SUPPORT = "help_support"
    const val ABOUT = "about"

    fun searchResults(query: String) = "search_results/$query"
    fun apartmentDetails(id: String) = "apartment_details/$id"
    fun imageGallery(id: String) = "image_gallery/$id"
    fun mapView(id: String) = "map_view/$id"
    fun amenities(id: String) = "amenities/$id"
    fun calendar(id: String) = "calendar/$id"
    fun guestSelection(id: String) = "guest_selection/$id"
    fun bookingSummary(id: String) = "booking_summary/$id"
    fun payment(id: String) = "payment/$id"
    fun bookingConfirmation(id: String) = "booking_confirmation/$id"
    fun bookingDetails(id: String) = "booking_details/$id"
    fun hostProfile(id: String) = "host_profile/$id"
    fun chat(id: String) = "chat/$id"
    fun reviews(id: String) = "reviews/$id"
}
